# Generated by Django 4.2 on 2023-04-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="transcript",
            field=models.TextField(blank=True, null=True),
        ),
    ]
