# Generated by Django 4.2 on 2023-04-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_video_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="description",
        ),
        migrations.RemoveField(
            model_name="video",
            name="genre",
        ),
        migrations.RemoveField(
            model_name="video",
            name="noOfRequestedWords",
        ),
        migrations.RemoveField(
            model_name="video",
            name="summary",
        ),
        migrations.RemoveField(
            model_name="video",
            name="title",
        ),
        migrations.RemoveField(
            model_name="video",
            name="transcript",
        ),
        migrations.AlterField(
            model_name="video",
            name="url",
            field=models.CharField(
                default="https://www.youtube.com/watch?v=9bZkp7q19f0", max_length=200
            ),
        ),
    ]
