# Generated by Django 4.2 on 2023-04-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_remove_video_description_remove_video_genre_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="genre",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="noOfRequestedWords",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="transcript",
            field=models.TextField(blank=True, null=True),
        ),
    ]
