# Generated by Django 4.2 on 2023-04-21 23:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_video_description_video_genre_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="genre",
            new_name="type",
        ),
        migrations.RemoveField(
            model_name="video",
            name="noOfRequestedWords",
        ),
    ]
